### PR TITLE
feat: modules support

### PR DESCRIPTION
**Pull request by alienvspredator**
**What this PR does / why we need it**:
``` Detailed description of PR; If no description, remove the block.
Add modules support to the session manager, define and implement standard `trust` and `database` modules.
```

**Special notes for your reviewer**:
``` If no notes, remove the block.
The modules are statically linked at built-time.
Custom-built session manager with other modules can be built by altering imports in the main.go file. The main() body remains unchanged (makes a call to maincmd.Main()).
```

**Release note**:
``` Release notes; If no release note is required, just write "NONE" within the block.
- Support statically linked modules at build time.
- Implement `trust` module with OIDC.
- Implement `database` module with pgxpool.
```

feat: module extensions

### CODE REVIEW

File: modules/oidctrust/module.go [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+
+func newModule() sessionmanager.Module {
+	return new(TrustModule)
+}
+
+func init() {
+	sessionmanager.RegisterModule(new(TrustModule))
+}
+
+// TrustModule is a module that implements sessionmanager.Trust interface. It's using a database providede by the
```
Comment (cb80) [inline modules/oidctrust/module.go]:
```suggestion
// TrustModule is a module that implements sessionmanager.Trust interface. It's using a database provided by the
```

File: internal/config/config.go [hunk 2]
```diff
@@ -3,13 +3,19 @@
 package config
 
 import (
+	"fmt"
+	"reflect"
 	"time"
 
+	"github.com/creasty/defaults"
+	"github.com/knadh/koanf/v2"
```
Comment (cb80) [inline internal/config/config.go:11]: We usually use viper for this, so do we really need koanf?
Especially as one of its deps `github.com/mitchellh/copystructure` is archived.

File: context.go [hunk 3]
```diff
@@ -0,0 +1,187 @@
...
+
+	mod := modInfo.New()
+	rv := reflect.ValueOf(mod)
+	if rv.Kind() == reflect.Pointer && rv.Elem().Kind() == reflect.Struct {
+		if err := cfg.UnmarshalExtension(mod); err != nil {
+			return nil, ModuleInfo{}, fmt.Errorf("unmarshaling extension %s: %w", modInfo.ID, err)
+		}
+	}
+
+	slogctx.Debug(c, "instantinated module", "module", modInfo.ID)
```
Comment (cb80) [inline context.go]:
```suggestion
	slogctx.Debug(c, "instantiated module", "module", modInfo.ID)
```

**Review by cb80 — CHANGES_REQUESTED** [review]

File: internal/config/config.go (hunk 2 above)
Comment (alienvspredator) [reply internal/config/config.go:11]: We can't use viper for this use-case. Viper can't parse and store ambiguous values, as well as some issues with Viper:
- viper breaks JSON, YAML, TOML, HCL language specs by https://github.com/spf13/viper/pull/635.
- hardcoded parsers

So we can't really use Viper here.

**Review by cb80 — CHANGES_REQUESTED** [review]
Please bump the chart version.

**Review by cb80 — DISMISSED** [review]

**Review by cb80 — DISMISSED** [review]

File: context.go [hunk 4]
```diff
@@ -0,0 +1,205 @@
...
+	typed, ok := mod.(T)
+	if !ok {
+		return zero, fmt.Errorf("module %q does not implement %s", id, reflect.TypeFor[T]())
+	}
+
+	return typed, nil
+}
+
+func (c *Context) LoadModule(cfg ExtensionConfig) (Module, error) {
+	before := len(c.modOrder)
```
Comment (petersbingham) [inline context.go]: `LoadAll` in `loader.go` provides graph validation, topo sort, and rollback. Is `LoadModule`/`LoadApp` still needed, or can it be removed? Tests still use it directly — if kept, should it be internal/test-only to prevent callers from bypassing graph validation?

File: modules/oidctrust/module.go [hunk 5]
```diff
@@ -0,0 +1,46 @@
...
+}
+
+func init() {
+	sessionmanager.RegisterModule(new(TrustModule))
+}
+
+// TrustModule is a module that implements sessionmanager.Trust interface. It's using a database provided by the
+// [dbModule] module which implements sessionmanager.DBModule.
+type TrustModule struct {
+	DBModule string `yaml:"dbModule" default:"database.module.pgxpool" dep:"sessionmanager.Database"`
```
Comment (petersbingham) [inline modules/oidctrust/module.go:23]: The `dep` struct tag (e.g. `dep:"sessionmanager.Database"`) here and in other place is a string and won't be validated until runtime — a typo compiles fine but fails at startup.

We could add a typed `Validate(ctx *Context) error` to the module interface to make a compile time check.

File: internal/business/apps.go [hunk 6]
```diff
@@ -0,0 +1,133 @@
...
+		if _, ok := cfg.Apps[name]; !ok {
+			return nil, fmt.Errorf("appsOrder references unknown app %q", name)
+		}
+		if !seen[name] {
+			seen[name] = true
+			order = append(order, name)
+		}
+	}
+
+	for name := range cfg.Apps {
```
Comment (petersbingham) [inline internal/business/apps.go:125]: We want to apply an ordering here?

File: loader.go [hunk 7]
```diff
@@ -0,0 +1,464 @@
...
+// Phase 3:
+// read dep-tagged fields via reflection and validate the whole graph
+// (every referenced ID present, satisfies its interface, no cycles),
+// aggregating all errors.
+//
+// Phase 4:
+// provision each node in the caller-supplied (flattened) order and
+// register it into the Context, rolling back on failure.
+//
+// The provisioning order in this increment is the flattened spec order; a
```
Comment (petersbingham) [inline loader.go]: Is this still relevant?

File: modules/standard/imports.go [hunk 8]
```diff
@@ -0,0 +1,13 @@
+package standard
+
+import (
+	_ "github.com/openkcm/session-manager/modules/app/grpcserver"
+	_ "github.com/openkcm/session-manager/modules/credentials/oauth2"
+	_ "github.com/openkcm/session-manager/modules/database/pgxpool"
+	_ "github.com/openkcm/session-manager/modules/grpc/oidcmapping"
```
Comment (petersbingham) [inline modules/standard/imports.go:7]: The legacy `oidcmapping` API is still actively used by the CMK tenant provisioner. We planning to update this at some point?

File: modules/oidctrust/module.go (hunk 5 above)
Comment (alienvspredator) [reply modules/oidctrust/module.go:23]: We can't do a compile-time check. It's a trade-off. But we effectively catch a typo here with unit tests, so a typo can't slip through a CI/CD pipeline. An example of a failed test (typo in Databas**r**)
Screenshot 2026-08-06 at 16 00 32

File: internal/business/apps.go (hunk 6 above)
Comment (alienvspredator) [reply internal/business/apps.go:125]: It's a function that resolve an order and returns an array of the apps how they start in order. Unless an app is listed in `appsOrder`, it's parser-defined.

File: loader.go (hunk 7 above)
Comment (alienvspredator) [reply loader.go]: Yes, that's how it actually works.

File: modules/standard/imports.go (hunk 8 above)
Comment (alienvspredator) [reply modules/standard/imports.go:7]: This is exactly why we ship the legacy oidcmapping API. It's a compatibility layer, until the API consumers haven't migrated to the new API. It'll be removed in the future, but we need to keep it for now.

File: loader.go (hunk 7 above)
Comment (petersbingham) [reply loader.go]: The comment says `flattened spec order` but the code calls `topoSort(pending)`. Maybe I've misunderstood, what exactly do you mean by "later change"?

File: internal/business/apps.go (hunk 6 above)
Comment (petersbingham) [reply internal/business/apps.go:125]: `Apps` is typed as `map[string]*App` so iteration order is non-deterministic regardless of YAML parse order. If parser-defined order is the intent, it would need to be a slice or an ordered map type.

File: modules/oidctrust/module.go (hunk 5 above)
Comment (petersbingham) [reply modules/oidctrust/module.go:23]: OK, that's fine.

File: modules/standard/imports.go (hunk 8 above)
Comment (petersbingham) [reply modules/standard/imports.go:7]: Yeah, that makes sense. Just wanted to know if we are planning to remove. Is there a ticket?

File: context.go (hunk 4 above)
Comment (alienvspredator) [reply context.go]: Good point. I've removed LoadModule/LoadApp

File: internal/business/apps.go (hunk 6 above)
Comment (alienvspredator) [reply internal/business/apps.go:125]: There's no intent to apply deterministic order here. It's only intended to apply when an app is explicitly listed in appsOrder. Otherwise it's non-deterministic.

File: modules/standard/imports.go (hunk 8 above)
Comment (alienvspredator) [reply modules/standard/imports.go:7]: So far no, we don't have a ticket yet… But we are planning to remove it once the consumers are migrated.

File: internal/business/apps.go (hunk 6 above)
Comment (petersbingham) [reply internal/business/apps.go:125]: That's fine, it's a nit. We can add if needed or issue in future.

File: loader.go (hunk 7 above)
Comment (alienvspredator) [reply loader.go]: Updated the comment.

**Review by petersbingham — DISMISSED** [review]

**Review by petersbingham — APPROVED** [review]

**Review by cb80 — APPROVED** [review]
